### ISSUE TITLE
Spelling mistake with regards to "Finish and Close" button

### ISSUE THREAD

**Issue by jlcalvano** [dermasmid/py-jsoneditor#5]
Small spelling mistake on title of "Finish and Close" button

![image](https://user-images.githubusercontent.com/34986483/153087116-420ae290-e7e0-45db-8a5a-8981e1b40a65.png)

Awesome job tho! Is will be my first contribute so I am submitted a PR right now

**Comment by dermasmid** [comment]
Thanks @jlcalvano for taking the time, much appreciated!
